version: "3.9"
services:
  redis:
    image: redis:7-alpine
    container_name: agrimatch-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: agrimatch-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
